.Dd May 10, 2015
.Dt BTINFO 1
.Os
.Sh NAME
.Nm btinfo
.Nd BitTorrent Protocol Daemon information
.Sh SYNOPSIS
.Nm btinfo
.Ar
.Sh EXAMPLES
List the torrent information for
.Pa osol-0906-x86.iso.torrent :
.Bd -literal
$ btinfo /var/torrents/osol-0906-x86.iso.torrent
Name: osol-0906-x86.iso
Info hash: 58aca632a9f68427a8ac8f58cafa7a72ca067dba
Tracker URLs: [ [ http://dlc.sun.com:6969/announce ] [ http://dlc.sun.com:16969/announce ] ]
Number of pieces: 1354
Piece size: 524288
Total size: 709871616
Number of files: 1
Files:
osol-0906-x86.iso (709871616)
.Ed
.Sh SEE ALSO
.Xr btcli 1 ,
.Xr btpd 1
.Sh AUTHORS
.An -nosplit
Current maintainers:
.Bl -bullet
.It
.An Marq Schneider Aq Mt queueRAM@gmail.com
.El
.Pp
Past contributors:
.Bl -bullet
.It
Richard Nyberg
.Aq Mt btpd@murmeldjur.se
.El
.Sh BUGS
Known bugs are listed at
.Lk http://github.com/btpd/btpd/issues .
.Pp
Before submitting a bug report,
please verify that you are running the latest version of
.Xr btpd 1 .
